# Generated by Django 5.0.6 on 2024-12-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0002_alter_totalsolutions_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('application', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('uom', models.CharField(max_length=50)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=255)),
                ('quotation_received_date', models.DateField()),
                ('lead_time', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_margin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
