# Generated by Django 5.0.6 on 2024-12-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='application',
            field=models.CharField(max_length=245),
        ),
    ]
